site_name: Shared Use Parking Model
nav:
  - Home: index.md
  - Postprocess: postprocess.md
  - About: about.md
theme: 
  name: mkdocs
  navigation_depth: 2
markdown_extensions:
  - toc:
      permalink: "#"